# Generated by Django 4.2.9 on 2024-01-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_author_alter_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
